### ISSUE TITLE
Matrix animation bug

### ISSUE THREAD

**Issue by Hunman** [fairyglade/ly#624]
After recently updating, a bunch of the letters start falling at the same time

**OS:** Arch Linux
**Installed version:** [ly-git](https://aur.archlinux.org/packages/ly-git) `0.6.0.r10.g3d8d8d6-1` (= commit 
`3d8d8d6`) from the aur (application reports `Ly version 1.0.0-dev`)
**Previous version:** `0.6.0.r4.g4ee2b3e` (= commit `4ee2b3e`)

![image](https://github.com/fairyglade/ly/assets/7405480/86b111a2-6939-4204-8881-e3a1abc5254c)

The commits between:
![image](https://github.com/fairyglade/ly/assets/7405480/f845cc30-5b31-4009-8251-f8f6f4af9c54)

**Comment by AnErrupTion** [comment]
@Hunman I believe this issue is now fixed in v1.0.0. Can you check, please?

**Comment by Hunman** [comment]
Updated it through the aur and now the version seems to be `Ly version 1.1.0-dev.4+dc8d143`, however the bug still persists above a certain window size

![image](https://github.com/fairyglade/ly/assets/7405480/4d6f7ad8-6ea3-4117-b4fc-8862dc5fb6c1)


In a 85 character wide window, Matrix seems to start correctly
![image](https://github.com/fairyglade/ly/assets/7405480/0d98c622-2b61-41b0-b76c-c24b7f8949ed)

But 86 characters and above the bug occurs still (only at the start)
![image](https://github.com/fairyglade/ly/assets/7405480/b9dc9601-6aad-4589-a3e1-685a9aa1b5c6)

**Comment by yannfill** [comment]
I confirm that the bug is still present in package version 1.0.0.-1 from extra on Arch.

**Comment by AnErrupTion** [comment]
@Hunman @yannfill Can you now check if it's fixed with master please?

**Comment by Hunman** [comment]
It seems to be working now

**Comment by yannfill** [comment]
I don't know if the commit was merged in 1.0.1 release but the bug is still there in the Arch package.

**Comment by AnErrupTion** [comment]
> I don't know if the commit was merged in 1.0.1 release but the bug is still there in the Arch package.

Ah yeah it wasn't, it's merged for v1.0.2, but that's not released yet.

**Comment by AnErrupTion** [comment]
@yannfill Ly v1.0.2 hit the repos, can you confirm the bug is fixed on your side please?

**Comment by AnErrupTion** [comment]
Great! Thanks for confirming!
